---
kind: Secret
apiVersion: v1
metadata:
  name: git-credentials-gitlab
  annotations:
    controller.devfile.io/mount-path: /home/theia/.git-credentials
  labels:
    controller.devfile.io/git-credential: "true"
    controller.devfile.io/watch-secret: "true"
type: Opaque